name: build for windows

on:
  # triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # allows you to run this workflow manually from the actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - run: choco list -l
      - run: choco install -y boost-msvc-14.2

      - run: cmake .
