name: build for windows

on:
  # triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # allows you to run this workflow manually from the actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Install boost
        uses: MarkusJx/install-boost@v2.0.0
        with:
          # A list of supported versions can be found here:
          # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
          boost_version: 1.73.0
          boost_install_dir: C:\\

      - run: dir c:\\boost
      - run: dir c:\\boost\\boost

      - run: cmake . -DBOOST_ROOT=C:/boost/boost
